[package]
name = "adventofcode2015"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name="common"
path="lib.rs"

[[bin]]
name="day01"
path="day01.rs"

[[bin]]
name="day02"
path="day02.rs"

[[bin]]
name="day03"
path="day03.rs"
